# Official docker image.
maven:build:
    image: maven:3.5.0-jdk-8-alpine
    script:
    - mvn clean install sonar:sonar

docker:build:
    image: docker:latest
    before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:CI_COMMIT_REF_SLUG"
